name: local_store
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  injectable: ^2.3.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  dart_code_metrics_presets: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
